### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by deadbytes** [foo123/ace-grammar#3]
What's the license to use and extend this project (it works great, by the way)?

**Comment by foo123** [comment]
Thanks nice to hear that, it is unlicence, or free as in free beer and free speech!

**Comment by foo123** [comment]
Actually latest update (which removed extra depedencies and refactored code) has a regression bug in that the worker error validators (for ACE) do not seem to work. It is going to be fixed (the syntax-highlight works fine though), but due to other projects do not have the time right now

**Comment by foo123** [comment]
Just to notify that new update in ace-grammar (v. 0.11) fixes issue with lint annotations in worker (as mentioned in previous comment of mine), plus some other changes (e.g make grammar specification easier, more BNF-like, etc..)

**Comment by foo123** [comment]
Uploaded v. 1.0 with full support for BNF-like syntax notation plus fixed tag matching actions
